const constants = {
    POST_PHOTO: 'POST_PHOTO',
//user uploads    
    GETTING_USER_PHOTOS: 'GETTING_USER_PHOTOS',
    GOT_USER_PHOTOS: 'GOT_USER_PHOTOS',
    ERROR_GETTING_PHOTOS: 'ERROR_GETTING_PHOTOS',

    DELETING_PHOTO: 'DELETING_PHOTO',
    DELETE_PHOTO: 'DELETE_PHOTO',

    EDITING_PHOTO: 'EDITING_PHOTO',
    EDIT_PHOTO: 'EDIT_PHOTO',
//loginstore
    STORE_LOGIN: 'STORE_LOGIN',
}

export default constants;